services:
  - type: web
    name: jira-lite-api
    env: docker
    rootDir: jira-lite/backend
    dockerfilePath: Dockerfile
    healthCheckPath: /health

  - type: static
    name: jira-lite-ui
    rootDir: jira-lite/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

